Release 0.1.1
UselessStudio/TeleOTP pull request #21
Opened 2024-04-02 12:09 UTC by LowderPlay

- Added analytics
- Added biometric unlock

2024-04-02 12:21 UTC, LowderPlay commented
Release preview is available at https://t.me/TeleOTPAppBot/preview

2024-04-02 12:28 UTC, LowderPlay reviewed
LGTM 😎

2024-04-02 15:55 UTC, lenchq commented on src/main.tsx
> +    <PlausibleAnalyticsProvider domain="teleotp.pages.dev" apiHost="https://analytics.gesti.tech/">
move apiHost to env var

2024-04-02 16:11 UTC, lenchq requested changes

2024-04-02 16:11 UTC, lenchq commented on src/main.tsx
> +    <PlausibleAnalyticsProvider domain="teleotp.pages.dev" apiHost="https://analytics.gesti.tech/">
move apiHost to env var

2024-04-02 16:11 UTC, lenchq commented on package.json
> +  "version": "0.1.1",
do a minor version bump instead (0.2.0)

2024-04-05 09:36 UTC, lenchq requested changes
need to also change version in package-lock.json

2024-04-05 13:25 UTC, lenchq approved these changes

2024-04-05 13:25 UTC, lenchq commented
ready to merge

2024-04-05 13:33 UTC, merged